import os
from dotenv import load_dotenv
from typing import TypedDict

load_dotenv()


class Config(TypedDict):
    # GLOBAL
    BYPASS: list[str]
    ENVIRONMENT: str
    # IBM
    WATSONX_API_URL: str
    WATSONX_API_KEY: str
    WATSONX_PROJECT_ID: str
    # Azure
    AZURE_SEARCH_API_URL: str
    AZURE_SEARCH_API_PRIMARY_ADMIN_KEY: str
    AZURE_SEARCH_API_INDEX: str
    AZURE_OPENAI_RESOURCE_URL: str
    AZURE_OPENAI_RESOURCE_KEY: str
    AZURE_OPENAI_DEPLOYMENT_MODEL: str
    AZURE_OPENAI_DEPLOYMENT_VERSION: str
    AZURE_OPENAI_DEPLOYMENT_URL: str
    AZURE_OPENAI_DEPLOYMENT_KEY: str
    AZURE_OPENAI_EMBEDDING_DEPLOYMENT_MODEL: str
    AZURE_OPENAI_EMBEDDING_DEPLOYMENT_KEY: str


config: Config = {
    "WATSONX_API_URL": os.getenv("WATSONX_API_URL"),
    "WATSONX_API_KEY": os.getenv("WATSONX_API_KEY"),
    "WATSONX_PROJECT_ID": os.getenv("WATSONX_PROJECT_ID"),
    "ENVIRONMENT": os.getenv("ENVIRONMENT"),
    "BYPASS": os.getenv("BYPASS").split(","),
    "AZURE_SEARCH_API_URL": os.getenv("AZURE_SEARCH_API_URL"),
    "AZURE_SEARCH_API_PRIMARY_ADMIN_KEY": os.getenv(
        "AZURE_SEARCH_API_PRIMARY_ADMIN_KEY"
    ),
    "AZURE_SEARCH_API_INDEX": os.getenv("AZURE_SEARCH_API_INDEX"),
    "AZURE_OPENAI_RESOURCE_URL": os.getenv("AZURE_OPENAI_RESOURCE_URL"),
    "AZURE_OPENAI_RESOURCE_KEY": os.getenv("AZURE_OPENAI_RESOURCE_KEY"),
    "AZURE_OPENAI_DEPLOYMENT_MODEL": os.getenv("AZURE_OPENAI_DEPLOYMENT_MODEL"),
    "AZURE_OPENAI_DEPLOYMENT_VERSION": os.getenv("AZURE_OPENAI_DEPLOYMENT_VERSION"),
    "AZURE_OPENAI_DEPLOYMENT_URL": os.getenv("AZURE_OPENAI_DEPLOYMENT_URL"),
    "AZURE_OPENAI_DEPLOYMENT_KEY": os.getenv("AZURE_OPENAI_DEPLOYMENT_KEY"),
    "AZURE_OPENAI_EMBEDDING_DEPLOYMENT_MODEL": os.getenv(
        "AZURE_OPENAI_EMBEDDING_DEPLOYMENT_MODEL"
    ),
    "AZURE_OPENAI_EMBEDDING_DEPLOYMENT_KEY": os.getenv(
        "AZURE_OPENAI_EMBEDDING_DEPLOYMENT_KEY"
    ),
}
